services:
  - type: web
    name: sanduiche-chefe
    env: node
    buildCommand: rm -rf node_modules && npm ci
    startCommand: node js/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/public
      sizeGB: 1 